runtime:
  kind: trtllm-serve

model:
  served_model_name: "meta-llama/Llama-3.2-3B-Instruct"
  hf_path: "models/llama32-3b"

compression:
  project: "llama32-3b-trt-compile"
  run_id: "run-001"

trtllm:
  port: 8000

deployment:
  namespace: "llama32-3b-serving-trt-engine"
  gpu_count: 1
